# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site #整站的基本信息
title: 乱码周刊 #网站标题
subtitle: #网站副标题
description: #网站描述
author: Naog #网站作者
language: zh-CN
timezone:

# URL #域名和文件结构
url: http://xote.tk #域名
root: /
permalink: :title.html
permalink_defaults: /404.html

# Directory #文件夹
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing #写文章选项
new_post_name: :title.md #新文章名称
default_layout: post #默认layout方式
titlecase: false # 把标题转换为 title case
external_link: true # 在新标签中打开链接
auto_spacing: true #在中文和英文之间加入空格
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false #把链接改为与根目录的相对位址
future: true
highlight: #代码高亮
  enable: true #是否启用
  line_number: false #是否显示行号
  tab_replace:

# Category & Tag #分类与标签
default_category: uncategorized
category_map:
	代码笔记: code
	善用佳软: skill
tag_map:

# Date / Time format #日期显示格式
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination #分页设置
per_page: 10
pagination_dir: page

# Extensions #插件主题
theme: tt

# Deployment
deploy:
  type: git
  message: update
  repo:
    github: https://github.com/naog/naog.github.io.git,master
    gitcafe: https://gitcafe.com/naog/naog.git,gitcafe-pages